DROP TABLE IF EXISTS book;
CREATE TABLE book (
    created_date timestamp NOT NULL,
    updated_date timestamp NOT NULL,
    book_id integer NOT NULL,
    isbn integer NOT NULL,
    book_title varchar(50) NOT NULL,
    book_author varchar(50) NOT NULL,
    PRIMARY KEY ("book_id")
);

ALTER TABLE public.book ALTER COLUMN book_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO book(isbn, book_title, book_author, created_date, updated_date)
VALUES(123456, 'The Alchemist', 'Paulo Coelho', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

